DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS logincredentials CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS stack CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS deck CASCADE;
DROP TABLE IF EXISTS tradings CASCADE;
DROP TABLE IF EXISTS battle CASCADE;


